#!/bin/sh
#
# postinstall script for osquery.pkg
#

# Display the license agreement
/usr/bin/osascript << EOT
tell application "System Events"
  activate
  set theAlertText to "License Agreement"
  set theAlertMessage to (do shell script "../license.txt")
  display dialog theAlertMessage buttons {"Agree", "Disagree"} default button "Disagree" cancel button "Disagree" with icon caution with title theAlertText
end tell
EOT