name: Build and Package osquery for macOS

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: macos-latest


        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Install Xcode coummand-line tools
              run: sudo xcode-select --install

            - name: Install osquery dependencies
              run: |
                brew install cmake glog gflags thrift
                pip3 install --user setuptools pexpect==3.3 psutil timeout_decorator six thrift==0.11.0 osquery


            - name: Build osquery
              run: |
                git clone https://github.com/osquery/osquery.git
                cd osquery
                make deps
                make -j$(sysctl -n hw.logicalcpu)

            - name: Create Package
              run: |
                mkdir -p pkg-root/usr/local/bin
                cp osquery/build/{osqueryi,osqueryd} pkg-root/usr/local/bin
                pkgbuild --root pkg-root --identifier com.vistar.osquery --version 1.0 --install-location /usr/local/bin osquery.pkg