name: Build osquery for macOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install macOS prerequisites
        run: |
          # Check if Xcode command-line tools are already installed
          xcode-select -p || xcode-select --install

          # Install other prerequisites using Homebrew
          brew install ccache git git-lfs cmake python clang-format flex bison
          pip3 install --user setuptools pexpect==3.3 psutil timeout_decorator six thrift==0.11.0 osquery

      - name: Download and build osquery source
        run: |
          git clone https://github.com/osquery/osquery
          cd osquery
          mkdir build
          cd build
          cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
          cmake --build . -j $(sysctl -n hw.ncpu)
      - name: Generating the package data
        run: |
            cd osquery/build
            mkdir package_data
            export DESTDIR=$(pwd)/package_data
            cmake --build . --target install

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: osquery
          path: osquery/build/package_data
  seleinum:
    runs-on: macos-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.x  
        - name: Install dependencies
          run: |
            pip install pyinstaller
           
        - name: install
          run: |
            pip install selenium
        - name: Build executable
          id: selenium
          run: |
            pyinstaller --onefile my_selenium.py
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: selenium
            path: ./dist/my_selenium 
